# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmProgress <- function(step, size = 0L) {
    invisible(.Call('_ganDataModel_dmProgress', PACKAGE = 'ganDataModel', step, size))
}

dmResetSub <- function() {
    invisible(.Call('_ganDataModel_dmResetSub', PACKAGE = 'ganDataModel'))
}

dmGetBatchSize <- function() {
    .Call('_ganDataModel_dmGetBatchSize', PACKAGE = 'ganDataModel')
}

dmGetMaxSize <- function() {
    .Call('_ganDataModel_dmGetMaxSize', PACKAGE = 'ganDataModel')
}

dmDataSourceRead <- function(inFileName) {
    invisible(.Call('_ganDataModel_dmDataSourceRead', PACKAGE = 'ganDataModel', inFileName))
}

dmGenerativeDataRead <- function(inFileName) {
    invisible(.Call('_ganDataModel_dmGenerativeDataRead', PACKAGE = 'ganDataModel', inFileName))
}

dmDataSourceGetNormalizedDataRandom <- function(rowCount) {
    .Call('_ganDataModel_dmDataSourceGetNormalizedDataRandom', PACKAGE = 'ganDataModel', rowCount)
}

dmDataSourceGetDataRandom <- function(percent) {
    .Call('_ganDataModel_dmDataSourceGetDataRandom', PACKAGE = 'ganDataModel', percent)
}

dmGenerativeDataGetNormalizedDataRandom <- function(rowCount) {
    .Call('_ganDataModel_dmGenerativeDataGetNormalizedDataRandom', PACKAGE = 'ganDataModel', rowCount)
}

dmGenerativeDataGetNormalizedDataRandomWithDensities <- function(rowCount) {
    .Call('_ganDataModel_dmGenerativeDataGetNormalizedDataRandomWithDensities', PACKAGE = 'ganDataModel', rowCount)
}

dmEvaluateCopyDataSourceGetNormalizedData <- function(row, rowCount) {
    .Call('_ganDataModel_dmEvaluateCopyDataSourceGetNormalizedData', PACKAGE = 'ganDataModel', row, rowCount)
}

dmGetDataSourceDimension <- function() {
    .Call('_ganDataModel_dmGetDataSourceDimension', PACKAGE = 'ganDataModel')
}

dmGetGenerativeDataDimension <- function() {
    .Call('_ganDataModel_dmGetGenerativeDataDimension', PACKAGE = 'ganDataModel')
}

dmGetNormalizedSize <- function() {
    .Call('_ganDataModel_dmGetNormalizedSize', PACKAGE = 'ganDataModel')
}

dmGetEvaluateCopyDataSourceNormalizedSize <- function() {
    .Call('_ganDataModel_dmGetEvaluateCopyDataSourceNormalizedSize', PACKAGE = 'ganDataModel')
}

dmBuildFileName <- function(fileName, extension) {
    .Call('_ganDataModel_dmBuildFileName', PACKAGE = 'ganDataModel', fileName, extension)
}

dmWriteWithReadingTrainedModel <- function(outFileName) {
    invisible(.Call('_ganDataModel_dmWriteWithReadingTrainedModel', PACKAGE = 'ganDataModel', outFileName))
}

dmWrite <- function(outFileName) {
    invisible(.Call('_ganDataModel_dmWrite', PACKAGE = 'ganDataModel', outFileName))
}

dmReadDataModel <- function(inFileName) {
    invisible(.Call('_ganDataModel_dmReadDataModel', PACKAGE = 'ganDataModel', inFileName))
}

dmEvaluateDataSourceRead <- function(inFileName) {
    invisible(.Call('_ganDataModel_dmEvaluateDataSourceRead', PACKAGE = 'ganDataModel', inFileName))
}

dmGetEvaluateCopyDataSourceNormalizedData <- function(row, rowCount) {
    .Call('_ganDataModel_dmGetEvaluateCopyDataSourceNormalizedData', PACKAGE = 'ganDataModel', row, rowCount)
}

dmGetEvaluateCopyDataSourceDenormalizedData <- function(row, rowCount) {
    .Call('_ganDataModel_dmGetEvaluateCopyDataSourceDenormalizedData', PACKAGE = 'ganDataModel', row, rowCount)
}

dmGetNumberVectorIndexNames <- function(numberVectorIndices) {
    .Call('_ganDataModel_dmGetNumberVectorIndexNames', PACKAGE = 'ganDataModel', numberVectorIndices)
}

dmGetValue <- function(level) {
    .Call('_ganDataModel_dmGetValue', PACKAGE = 'ganDataModel', level)
}

dmGenerativeDataGetNormalizedData <- function(row, rowCount) {
    .Call('_ganDataModel_dmGenerativeDataGetNormalizedData', PACKAGE = 'ganDataModel', row, rowCount)
}

dmGetRow <- function(index) {
    .Call('_ganDataModel_dmGetRow', PACKAGE = 'ganDataModel', index)
}

dmReadVolumeElementGraph <- function(inFileName) {
    invisible(.Call('_ganDataModel_dmReadVolumeElementGraph', PACKAGE = 'ganDataModel', inFileName))
}

dmWriteVolumeElementGraph <- function(outFileName) {
    invisible(.Call('_ganDataModel_dmWriteVolumeElementGraph', PACKAGE = 'ganDataModel', outFileName))
}

dmAddVolumeElementsSub <- function(volumeElementValues, dimensions, indexBegin, level = 0.0) {
    invisible(.Call('_ganDataModel_dmAddVolumeElementsSub', PACKAGE = 'ganDataModel', volumeElementValues, dimensions, indexBegin, level))
}

dmBuildVolumeElements <- function() {
    invisible(.Call('_ganDataModel_dmBuildVolumeElements', PACKAGE = 'ganDataModel'))
}

dmBuildVolumeElementTree <- function() {
    invisible(.Call('_ganDataModel_dmBuildVolumeElementTree', PACKAGE = 'ganDataModel'))
}

dmBuildVolumeElementGraph <- function() {
    invisible(.Call('_ganDataModel_dmBuildVolumeElementGraph', PACKAGE = 'ganDataModel'))
}

dmAddVolumeElementGraph <- function() {
    invisible(.Call('_ganDataModel_dmAddVolumeElementGraph', PACKAGE = 'ganDataModel'))
}

dmBuildMetricSubspacesSub <- function() {
    .Call('_ganDataModel_dmBuildMetricSubspacesSub', PACKAGE = 'ganDataModel')
}

dmGetGenerativeDataRandom <- function(percent) {
    .Call('_ganDataModel_dmGetGenerativeDataRandom', PACKAGE = 'ganDataModel', percent)
}

dmGetMetricSubspaceDenormalizedGenerativeData <- function(level, metricSubspaceIndex, percent, boundary = FALSE) {
    .Call('_ganDataModel_dmGetMetricSubspaceDenormalizedGenerativeData', PACKAGE = 'ganDataModel', level, metricSubspaceIndex, percent, boundary)
}

dmGetMetricSubspaceIndices <- function(level, labels) {
    .Call('_ganDataModel_dmGetMetricSubspaceIndices', PACKAGE = 'ganDataModel', level, labels)
}

dmGetAdjacentVolumeElementIndices <- function(index) {
    .Call('_ganDataModel_dmGetAdjacentVolumeElementIndices', PACKAGE = 'ganDataModel', index)
}

dmGetMax <- function(i) {
    .Call('_ganDataModel_dmGetMax', PACKAGE = 'ganDataModel', i)
}

dmGetMin <- function(i) {
    .Call('_ganDataModel_dmGetMin', PACKAGE = 'ganDataModel', i)
}

#' Get levels for metric subspaces
#'
#' Get levels for metric subspaces in a data model.
#'
#' @return Vector of levels
#' @export
#'
#' @examples
#' \dontrun{
#' dmRead("dm.bin", "gd.bin")
#' dmGetLevels()}
dmGetLevels <- function() {
    .Call('_ganDataModel_dmGetLevels', PACKAGE = 'ganDataModel')
}

#' Get metric subspace properties for a level
#'
#' Get properties of metric subspaces in a data model for a level.
#'
#' @param level Level for metric subspaces
#'
#' @return List of list containing label and size of contained generative data for metric subspaces
#' @export
#'
#' @examples
#' \dontrun{
#' dmRead("dm.bin", "gd.bin")
#' dmGetMetricSubspaceProperties(0.73)}
dmGetMetricSubspaceProperties <- function(level) {
    .Call('_ganDataModel_dmGetMetricSubspaceProperties', PACKAGE = 'ganDataModel', level)
}

dmRemoveMetricSubspacesSub <- function(level) {
    invisible(.Call('_ganDataModel_dmRemoveMetricSubspacesSub', PACKAGE = 'ganDataModel', level))
}

dmNormalizedDataRecord <- function(dataRecord) {
    .Call('_ganDataModel_dmNormalizedDataRecord', PACKAGE = 'ganDataModel', dataRecord)
}

dmGetMetricSubspacesSub <- function(dataRecord, level) {
    .Call('_ganDataModel_dmGetMetricSubspacesSub', PACKAGE = 'ganDataModel', dataRecord, level)
}

dmMetricSubspaceLabelPointsSub <- function(lLevel, rLevel, percent, columnIndices, lLabels) {
    .Call('_ganDataModel_dmMetricSubspaceLabelPointsSub', PACKAGE = 'ganDataModel', lLevel, rLevel, percent, columnIndices, lLabels)
}

dmSortLevelIndices <- function(levels) {
    .Call('_ganDataModel_dmSortLevelIndices', PACKAGE = 'ganDataModel', levels)
}

